language: python
python:
    - "2.7"
install: 
    - sudo apt-get build-dep python-pygame
    - sudo apt-get install mercurial
    - pip install hg+http://bitbucket.org/pygame/pygame
script: 
    - make tests
