#! /bin/bash

requirements=()
getArray() {
    i=0
    while read line
    do
        requirements[i]=$line
        i=$(($i+1))
    done < $1
}

echo "\nWARNING: You must manually install Pygame if it's not already installed.\n"

echo "Verifying required Python dependencies are installed."
getArray ".requirements.txt"
for requirement in "${requirements[@]}"
do
    pip_req_name=$requirement

    if echo "$requirement" | grep ">=" 1>/dev/null; then
        pip_req_name=$(echo $requirement | awk -F'>=' '{print $1}')
    elif echo "$requirement" | grep ">" 1>/dev/null; then
        pip_req_name=$(echo $requirement | awk -F'>' '{print $1}')
    elif echo "$requirement" | grep "==" 1>/dev/null; then
        pip_req_name=$(echo $requirement | awk -F'==' '{print $1}')
    fi

    if ! pip list | grep "$pip_req_name" 1>/dev/null; then
        echo "Required dependency not found: $pip_req_name"
        echo "Attempting to install: $pip_req_name"
        sudo pip install "$requirement"

        if ! pip list | grep "$pip_req_name" 1>/dev/null; then
            echo "Failed to install: $pip_req_name"
            echo "Aborting..."
            exit 1
        fi
    fi

done

echo "All dependencies found."
echo "Starting Zol."

make main
